name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
          description: Provide the Ingress URL
          required: true
          type: string  
    # outputs:
    #   application-url:
    #     value: ${{ jobs.integration-test.URL }}


jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ inputs.ingress-url }}'
        run: |
              # curl https://$URL/live -s -k | jq -r .status | grep -i live
              # if [ -z "$URL" ]; then
              #   echo "❌ ERROR: ingress-url input is empty!"
              #   exit 1
              # fi
              # echo "✅ Checking endpoint: https://$URL/live"
              # curl https://$URL/live -s -k | jq -r .status | grep -i live

              echo "Testing Mongo connection via Docker..."
              docker run --rm mongo:7.0 mongosh "$URL" --eval "db.runCommand({ ping: 1 })"
             


      
